// 1sc_search_dmgd_unique
/*
	Description:
	When a searchable container is damaged
	the items inside inside may also be damaged.
	A damaged item is removed from hidden loot 
	and replaced by a broken item
	
	Incase the chest hadden't been opened yet this
	script also generates loot, hence there are a
	Unique, High, Norm and Low versions.
*/
// By System_Crush
// 25-7-07
#include "1sc_searchable"
#include "1sc_searchable_treasure"

void main()
	{

	}