const float ACR_DROPGOLD_MAXIMUM_DROP_DISTANCE = 4.0f;
const string ACR_DROPGOLD_AMOUNT = "ACR_DROPGOLD_AMOUNT";

const string ACR_GUI_DROPGOLD_WINDOW_XML = "golddropinputbox.xml";
const string ACR_GUI_DROPGOLD_WINDOW = "SCREEN_GOLD_DROP";

const string ACR_GUI_DROPGOLD_AMOUNT_FIELD = "inputbox";
const string ACR_GUI_DROPGOLD_AMOUNT_ADD = "add";
const string ACR_GUI_DROPGOLD_AMOUNT_SUBTRACT = "subtract";
const string ACR_GUI_DROPGOLD_AMOUNT_ALL = "all";
