////////////////////////////////////////////////////////////////////////////////
// Wand System
// Original Scripter:  Caos81      Design: Caos81
//------------------------------------------------------------------------------
// Last Modified By:   Caos81           28/01/2009
//------------------------------------------------------------------------------
////////////////////////////////////////////////////////////////////////////////

// Set this constant to:
// TRUE -> Item Level Restricion enabled
// FALSE -> Item Level Restriction disabled
const int ITEM_LEVEL_RESTRICTION = FALSE;

// Set this constant to:
// TRUE -> with DMFI UI integration
// FALSE -> without DMFI UI integration
const int DMFI = TRUE;

// Set this constant to:
// TRUE -> Store UI settings within BioWare database
// FALSE -> Don't store any UI settings
const int STORE_SETTINGS = TRUE;