#
# This project constructs ALFA-Campaign creature resources.
#

!include $(PROJECT_SOURCE_ROOT)\makefile.def

all:
	@copy /y *.UTC $(OUTPUTDIR)\ >NUL

clean:
	@if exist $(OUTPUTDIR)\*.UTC del $(OUTPUTDIR)\*.UTC